### ISSUE TITLE
Enabling Authentication breaks application login

### ISSUE THREAD

**Issue by andyzukunft** [YunoHost-Apps/backrest_ynh#9]
I installed Backrest to Yunohost (default location). On first login I set the required admin account. Directly afterwards I went to settings and disabled "Disable Authentication". Now when I visit the page I am requested to login. After I do so the page reloads and I have to login again.

Deinstalling did not solve the issue. Can you tell me where the configuration is stored so I can delete it using the console?

**Comment by DeMiro5001** [comment]
All the app data are in /home/yunohost.app/backrest
I will add this information to the admin documentation.

**Comment by andyzukunft** [comment]
Hey, are you sure? I just deleted the folder, reinstalled the app and it starts up requesting a login. Meaning: it does not request to create an account.

![image](https://github.com/user-attachments/assets/4db5605e-8204-4676-b917-c58cac807789)

**Comment by DeMiro5001** [comment]
You're right.
It's in `/root/.config/backrest/config.json`

**Comment by DeMiro5001** [comment]
@andyzukunft did you get it working?

**Comment by andyzukunft** [comment]
Ahh sorry, I did not see any notification. I just wanted to report that after upgrading to the newest version the system started with a new onboarding process.

It is working now and I am not enabling authentication within the app. Thanks.
